language: elixir
elixir:
  - 1.10.2
otp_release:
  - 22.1.8
services:
  - postgresql
env:
  - MIX_ENV=test
before_script:
  - mix ecto.setup
script:
  - mix do deps.get, coveralls.json
# See: github.com/dwyl/repo-badges#documentation
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - _build
  - deps
